<?php

namespace AppBundle\Repository;

/**
 * ProjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectRepository extends \Doctrine\ORM\EntityRepository
{
    public function searchByTitle($name)
    {
        $qb = $this->createQueryBuilder('p')
            ->select('p.id, p.title')
            ->where('p.title LIKE :name')
            ->setParameter('name', '%'.$name.'%');

        return $qb->getQuery()->getResult();
    }
}
