parameters:
    #parameter_name: value

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    AppBundle\:
        resource: '../../src/AppBundle/*'
        exclude: '../../src/AppBundle/{Entity,Repository,Tests}'

    AppBundle\Controller\:
        resource: '../../src/AppBundle/Controller'
        public: true
        tags: ['controller.service_arguments']

    authentication.handler.login_success_handler:
        class: AppBundle\Security\LoginSuccessHandler
        arguments: ['@router', '@security.authorization_checker']

    appbundle.request_listener:
        class: AppBundle\EventListener\RequestListener
        arguments: ['@router', '@security.authorization_checker']
        tags:
            - { name: 'kernel.event_listener', event: 'kernel.request', method: 'onKernelRequest' }

    appbundle.logger_service:
        class: AppBundle\Service\Logger
        public: true
        arguments: ['@doctrine.orm.entity_manager']

    login_listener:
        # path of the previously created class
        class:  AppBundle\Listener\LoginListener
        arguments: ["@fos_user.user_manager"]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

    AppBundle\Form\ProjectType:
        arguments: ['@doctrine.orm.entity_manager']
        tags: [form.type]
